### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by shivanshsharma13** [IronManCool001/Covid-Win10-Notifier#1]
I am getting an attribute error in a line 12 of main.py. It says,

`AttributeError: 'function' object has no attribute 'confirmed'`

Steps I followed, 

- git clone <repo>
- pip install -r requirements.txt
- python main.py

**Comment by LegacyDebaditya** [comment]
Please check the [bitbucket repository](https://DebadityaMalakar@bitbucket.org/DebadityaMalakar/covid-win10-notifier.git) it may help you.You can clone the repository using the following command: 
git clone https://DebadityaMalakar@bitbucket.org/DebadityaMalakar/covid-win10-notifier.git
