### ISSUE TITLE
Minor Error

### ISSUE THREAD

**Issue by Vishnu-Joshi-18** [IronManCool001/Covid-Win10-Notifier#3]
I really appreciate this initiative , however , as I was going though the code , I couldn't help but notice something.
<img width="1033" alt="Screenshot 2020-10-23 at 11 45 43 AM" src="https://user-images.githubusercontent.com/68434268/96962932-6c4eaa00-1525-11eb-95b9-4b89cbe61447.png">

The last line of the function showInfo()  says 
`toast.show_toast(title , message, icon_path='C://whatever//the//path//is.ico' )`

This would only work on your system and if someone attempts to run it in their system , they would receive an error saying "Could not find the .ico file".

I suggest replacing the full path with the relative path. It should look something like this 
`toast.show_toast(title , message, icon_path='covid.ico' )`

I hope this helps you 👍

**Comment by LegacyDebaditya** [comment]
Thanks for pointing out the error you could access the exe present in the
dist folder.And can you make gui using python.

**Comment by LegacyDebaditya** [comment]
The issue is now solved you can check the updated python main.py file.
